//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmID
    {
        public AdmID()
        {
            this.AdmDatas = new HashSet<AdmData>();
        }
    
        public int ID_Code { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string Father { get; set; }
        public short Sex { get; set; }
        public string ShNum { get; set; }
        public string Birth_Date { get; set; }
        public int Birth_Place { get; set; }
        public int Sh_Place { get; set; }
        public short Married_Code { get; set; }
        public string Adress { get; set; }
        public short Mazhab_Code { get; set; }
        public short Work { get; set; }
        public short Work_Place { get; set; }
        public string Place { get; set; }
        public string SFamily { get; set; }
        public string SName { get; set; }
        public string SFather { get; set; }
        public string NationalCode { get; set; }
        public string MobileNo { get; set; }
        public string EMailAddress { get; set; }
        public string EmergCardNum { get; set; }
        public Nullable<short> BloodGroup { get; set; }
        public short CountryCode { get; set; }
        public short DiseaseTag { get; set; }
        public short Nationality { get; set; }
        public string PatientUID { get; set; }
        public short StudyDegree { get; set; }
        public short StayType { get; set; }
        public bool IsAnonymous { get; set; }
    
        public virtual ICollection<AdmData> AdmDatas { get; set; }
    }
}
