//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admission> Admissions { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Cardiology> Cardiologys { get; set; }
        public virtual DbSet<ChiefComplaint> ChiefComplaints { get; set; }
        public virtual DbSet<Collegian> Collegians { get; set; }
        public virtual DbSet<Digestion> Digestions { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<FollowUp> FollowUps { get; set; }
        public virtual DbSet<Gynocology> Gynocologys { get; set; }
        public virtual DbSet<HistoryDiseas> HistoryDiseases { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Internal> Internals { get; set; }
        public virtual DbSet<KindOfTherapy> KindOfTherapys { get; set; }
        public virtual DbSet<Laboratory> Laboratories { get; set; }
        public virtual DbSet<Lung> Lungs { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PhysicalExamination> PhysicalExaminations { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<VitalSign> VitalSigns { get; set; }
    }
}
