//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public Hospital()
        {
            this.Admissions = new HashSet<Admission>();
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int HospitalId { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Admission> Admissions { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual University University { get; set; }
    }
}
