//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratory
    {
        public int LaboratoryId { get; set; }
        public Nullable<int> VisitId { get; set; }
        public Nullable<System.DateTime> LeadTime { get; set; }
        public string Mg { get; set; }
        public string FBS { get; set; }
        public string Hb1AC { get; set; }
        public string BUN { get; set; }
        public string Cr { get; set; }
        public string Na { get; set; }
        public string K { get; set; }
        public string Ca { get; set; }
        public string Chol { get; set; }
        public string LDL { get; set; }
        public string HDL { get; set; }
        public string TG { get; set; }
        public string VitOHD3 { get; set; }
        public string CTnI { get; set; }
        public string CKMB { get; set; }
        public string AST { get; set; }
        public string ALT { get; set; }
        public string ALP { get; set; }
        public string BiL { get; set; }
        public string PSA { get; set; }
        public string TSH { get; set; }
        public string T3 { get; set; }
        public string T4 { get; set; }
        public string T3RU { get; set; }
    
        public virtual Visit Visit { get; set; }
    }
}
