//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public University()
        {
            this.Collegians = new HashSet<Collegian>();
            this.Hospitals = new HashSet<Hospital>();
        }
    
        public int UniversityId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Collegian> Collegians { get; set; }
        public virtual ICollection<Hospital> Hospitals { get; set; }
    }
}
