//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public Visit()
        {
            this.Cardiologys = new HashSet<Cardiology>();
            this.ChiefComplaints = new HashSet<ChiefComplaint>();
            this.Digestions = new HashSet<Digestion>();
            this.FollowUps = new HashSet<FollowUp>();
            this.Gynocologys = new HashSet<Gynocology>();
            this.Internals = new HashSet<Internal>();
            this.Laboratories = new HashSet<Laboratory>();
            this.Lungs = new HashSet<Lung>();
            this.PhysicalExaminations = new HashSet<PhysicalExamination>();
            this.VitalSigns = new HashSet<VitalSign>();
        }
    
        public int VisitId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public Nullable<int> KindOfTherapyId { get; set; }
        public Nullable<int> AdmissionId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> CollegianId { get; set; }
        public Nullable<System.DateTime> DateOfStay { get; set; }
    
        public virtual ICollection<Cardiology> Cardiologys { get; set; }
        public virtual ICollection<ChiefComplaint> ChiefComplaints { get; set; }
        public virtual Collegian Collegian { get; set; }
        public virtual ICollection<Digestion> Digestions { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual ICollection<FollowUp> FollowUps { get; set; }
        public virtual ICollection<Gynocology> Gynocologys { get; set; }
        public virtual ICollection<Internal> Internals { get; set; }
        public virtual KindOfTherapy KindOfTherapy { get; set; }
        public virtual ICollection<Laboratory> Laboratories { get; set; }
        public virtual ICollection<Lung> Lungs { get; set; }
        public virtual ICollection<PhysicalExamination> PhysicalExaminations { get; set; }
        public virtual ICollection<VitalSign> VitalSigns { get; set; }
    }
}
