//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmData
    {
        public int Adm_Code { get; set; }
        public int ID_Code { get; set; }
        public string Date { get; set; }
        public string Bast_Date { get; set; }
        public short PType { get; set; }
        public short Bimeh_Code { get; set; }
        public string Bimeh_Num { get; set; }
        public short Part_Code { get; set; }
        public Nullable<short> Bed_Code { get; set; }
        public bool isDis { get; set; }
        public string DisDate { get; set; }
        public short Bimeh2_Code { get; set; }
        public string Bimeh2_Num { get; set; }
        public string Police { get; set; }
        public short Pers_Code { get; set; }
        public string MName { get; set; }
        public string MAdress { get; set; }
        public int Dr_Code { get; set; }
        public short From_Hospital_Code { get; set; }
        public short To_Hospital_Code { get; set; }
        public string Note { get; set; }
        public bool isBefore { get; set; }
        public short BeforeNum { get; set; }
        public short BeforeBastNum { get; set; }
        public string Diagnosis { get; set; }
        public short DisPersonCode { get; set; }
        public short DisType { get; set; }
        public string DisAdvise { get; set; }
        public short BastDay { get; set; }
        public string DieDate { get; set; }
        public short DieTimeStatus { get; set; }
        public short AutopsyNum { get; set; }
        public short HelpNum { get; set; }
        public byte NewOprType { get; set; }
        public short AdmWardCode { get; set; }
        public bool isBedAsign { get; set; }
        public short AgeGroup { get; set; }
        public bool isBedDis { get; set; }
        public bool isMCard { get; set; }
        public bool isEmerg { get; set; }
        public short MBimehCode { get; set; }
        public string BimehEndDate { get; set; }
        public bool isBimehEndDate { get; set; }
        public int AdmPrePayPrice { get; set; }
        public string HappenPlace { get; set; }
        public short Age { get; set; }
        public short AgeMon { get; set; }
        public byte AgeDay { get; set; }
        public bool isFix { get; set; }
        public string FixDate { get; set; }
        public short FixPersCode { get; set; }
        public string Adress2 { get; set; }
        public bool isVIP { get; set; }
        public short PartServiceCode { get; set; }
        public string MBimehNum { get; set; }
        public string PostalCode { get; set; }
        public string Tel { get; set; }
        public bool isEmergCard { get; set; }
        public string EmergCardNum { get; set; }
        public short BimehIntroStatus { get; set; }
        public short BimehCtrlStatus { get; set; }
        public int InDrCode { get; set; }
        public short ReferType { get; set; }
        public string BDate { get; set; }
        public short Bimeh3Code { get; set; }
        public string Bimeh3Num { get; set; }
        public short DiagCode { get; set; }
        public Nullable<double> Weight { get; set; }
        public string MRelation { get; set; }
        public short EmergStatus { get; set; }
        public Nullable<double> Height { get; set; }
        public string Explain2 { get; set; }
        public short InsState { get; set; }
        public string InsSendDate { get; set; }
        public string InsRecDate { get; set; }
        public short InsState2 { get; set; }
        public string InsSendDate2 { get; set; }
        public string InsRecDate2 { get; set; }
        public string BimehSerialNo { get; set; }
        public Nullable<short> AdmBimehPageNum { get; set; }
        public int ReferNDr { get; set; }
        public string ReferCode { get; set; }
        public Nullable<short> BimehMandatoryType { get; set; }
        public bool isNotAcceptYaraneh { get; set; }
        public string HamrahMobileNo { get; set; }
        public string SepasCompositionIDLab { get; set; }
        public string SepasCompositionIDBed { get; set; }
        public string SepasCompositionIDInpatient { get; set; }
        public Nullable<short> DisPersonalReason { get; set; }
        public string HusbandFamily { get; set; }
        public string HusbandName { get; set; }
        public string HusbandNationalCode { get; set; }
        public Nullable<short> BimehRelation { get; set; }
        public Nullable<short> BimehPersonCode { get; set; }
        public Nullable<short> CrisisStatus { get; set; }
        public string SepasCompositionIDDeath { get; set; }
        public string DisBailOutExplain { get; set; }
        public string SBimehSerialNo { get; set; }
        public short PartCodeFirst { get; set; }
        public Nullable<bool> IsHistoryDone { get; set; }
        public string DisOrderDate { get; set; }
    
        public virtual AdmID AdmID { get; set; }
        public virtual Part_List Part_List { get; set; }
    }
}
