//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int AdmissionId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> DateOfStay { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Department Department { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
