//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShafaEntities : DbContext
    {
        public ShafaEntities()
            : base("name=ShafaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmData> AdmDatas { get; set; }
        public virtual DbSet<AdmID> AdmIDs { get; set; }
        public virtual DbSet<Part_List> Part_List { get; set; }
        public virtual DbSet<EMRCardiologyView> EMRCardiologyViews { get; set; }
        public virtual DbSet<EMRWomanView> EMRWomanViews { get; set; }
        public virtual DbSet<EMRInternalView> EMRInternalViews { get; set; }
        public virtual DbSet<EMRLungView> EMRLungViews { get; set; }
        public virtual DbSet<EMRDigestionView> EMRDigestionViews { get; set; }
    }
}
