//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryDiseas
    {
        public int HistoryDiseaseId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<System.DateTime> LeadTime { get; set; }
        public string Description { get; set; }
    }
}
