//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public Hospital()
        {
            this.Clinics = new HashSet<Clinic>();
            this.Departments = new HashSet<Department>();
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int HospitalId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Clinic> Clinics { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}
