//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part_List
    {
        public Part_List()
        {
            this.AdmDatas = new HashSet<AdmData>();
        }
    
        public short Code { get; set; }
        public string Name { get; set; }
        public string Explain { get; set; }
        public short Group_Code { get; set; }
        public short Type { get; set; }
        public short PricePartCode { get; set; }
        public short ADSCode { get; set; }
        public short ADSBedCount { get; set; }
        public string Tel { get; set; }
        public short FloorNo { get; set; }
        public short ClinicGroupCode { get; set; }
        public string LinkAcntCode { get; set; }
        public string LinkAcntHPartCode { get; set; }
        public bool isOpr { get; set; }
        public bool isBabyAdm { get; set; }
        public short PercasePartCode { get; set; }
        public short AmPmStatus { get; set; }
        public int CashPartStatus { get; set; }
        public string LabPaperCode3PartCode { get; set; }
        public Nullable<short> PrgCodeAssign { get; set; }
        public string PartNameSummary { get; set; }
        public bool isAcceptOrder { get; set; }
        public short BimehDiskPartOrder { get; set; }
        public int BimehLinkDrugCode { get; set; }
        public bool IsAcceptEmerg { get; set; }
        public bool IsSuppress { get; set; }
        public short PartGroupCode { get; set; }
        public short MaxServiceCountInPaper { get; set; }
        public short PartGroupCode2 { get; set; }
        public string SepasPartCode { get; set; }
        public short DwPartCode { get; set; }
        public bool HusbandDataMandatory { get; set; }
        public bool IsYaranehVisit { get; set; }
        public bool IsIncomeHide { get; set; }
        public short AccessWardGroupCode { get; set; }
    
        public virtual ICollection<AdmData> AdmDatas { get; set; }
    }
}
