//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Woman
    {
        public int WomanId { get; set; }
        public Nullable<int> VisitId { get; set; }
        public Nullable<int> HospitalizationId { get; set; }
        public Nullable<System.DateTime> LeadTime { get; set; }
        public string Dch { get; set; }
        public string Lch { get; set; }
        public string Ab { get; set; }
        public string P { get; set; }
        public string G { get; set; }
        public string BloodGroup { get; set; }
        public string Rh { get; set; }
        public string CaesareanNo { get; set; }
        public string VantvnzNo { get; set; }
        public string PreviousBirthWeight { get; set; }
        public string LastPregnancy { get; set; }
        public string NaturalChildbirthNo { get; set; }
        public string EDCAccordingLMP { get; set; }
        public string EDCAccordingSonography { get; set; }
        public string FirstSonographyResult { get; set; }
        public string SecondSonographyResult { get; set; }
        public string FirstLabResult { get; set; }
        public string SecondLabResult { get; set; }
        public string PreviousPregnancyWeight { get; set; }
        public string Stature { get; set; }
        public string BMI { get; set; }
        public string HistoryBreastDiseases { get; set; }
        public string HistoryTakingCertainMedications { get; set; }
        public string HistoryVaccination { get; set; }
    
        public virtual Hospitalization Hospitalization { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
